"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { AlertTriangle, Award, CheckCircle2, Gift, Plus, RefreshCw, ShieldAlert, Sparkles, Users, WalletCards } from "lucide-react";
import { AppLayout } from "@/components/layout/AppLayout";
import { Button } from "@/components/ui/Button";
import { EmptyState, ErrorState, Field, FilterTabs, LoadingState, Modal, ModuleHeader, StatGrid, StatusBadge, Toast, inputClass, textareaClass } from "@/components/modules/ModulePrimitives";
import { apiFetch } from "@/lib/org";

type Program = { id: string; name: string; description: string | null; status: string; activeVersionId: string | null; updatedAt: string };
type Account = { id: string; programId: string; programName: string; contactId: string; firstName: string; lastName: string | null; email: string | null; currentBalance: number; lifetimeEarned: number; lifetimeRedeemed: number; tierName: string | null; status: string };
type Transaction = { id: string; accountId: string; points: number; status: string; transactionType: string; sourceType: string; description: string | null; occurredAt: string };
type Referral = { id: string; programId: string; referrerContactId: string; referredContactId: string | null; referralCodeHint: string; status: string; createdAt: string };
type Review = { id: string; transactionId: string | null; referralId: string | null; riskLevel: string; status: string; reasonCodes: string[]; createdAt: string };
type Contact = { id: string; firstName: string; lastName: string | null; email: string | null };
type Dashboard = { summary: { programs: number; activePrograms: number; accounts: number; pointsOutstanding: number; lifetimeEarned: number; lifetimeRedeemed: number; heldTransactions: number; openFraudReviews: number; referrals: number; rewardedReferrals: number }; programs: Program[]; accounts: Account[]; transactions: Transaction[]; referrals: Referral[]; reviews: Review[]; methodology: string };
type ModalName = "program" | "account" | "transaction" | "referral" | null;

function fullName(first?: string | null, last?: string | null) { return `${first ?? ""} ${last ?? ""}`.trim() || "Unnamed customer"; }
function number(value: number) { return new Intl.NumberFormat("en-US").format(value); }

export default function LoyaltyPage() {
  const [data, setData] = useState<Dashboard | null>(null);
  const [contacts, setContacts] = useState<Contact[]>([]);
  const [tab, setTab] = useState("accounts");
  const [modal, setModal] = useState<ModalName>(null);
  const [form, setForm] = useState<Record<string, string>>({});
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");
  const [toast, setToast] = useState<{ message: string; type?: "success" | "error" } | null>(null);
  const [oneTimeCode, setOneTimeCode] = useState("");

  const load = useCallback(async () => {
    setLoading(true); setError("");
    try {
      const [dashboardResponse, contactsResponse] = await Promise.all([apiFetch("/api/loyalty/dashboard"), apiFetch("/api/contacts?limit=200")]);
      const [dashboard, contactPayload] = await Promise.all([dashboardResponse.json(), contactsResponse.json()]);
      if (!dashboardResponse.ok) throw new Error(dashboard.error ?? "Loyalty data could not be loaded");
      if (!contactsResponse.ok) throw new Error(contactPayload.error ?? "Contacts could not be loaded");
      setData(dashboard.data); setContacts(contactPayload.data);
    } catch (caught) { setError(caught instanceof Error ? caught.message : "Loyalty data could not be loaded"); }
    finally { setLoading(false); }
  }, []);
  useEffect(() => { void Promise.resolve().then(load); }, [load]);
  const activePrograms = useMemo(() => data?.programs.filter((item) => item.status === "active" && item.activeVersionId) ?? [], [data]);

  function open(name: ModalName) { setForm({ currencyName: "Points", maxPointsPerTransaction: "10000", dailyEarnLimit: "25000", fraudReviewThreshold: "5000", referralReward: "250", tiers: "Member | 0\nGold | 1000 | Priority support" }); setModal(name); }
  async function request(path: string, body: Record<string, unknown>, success: string, method = "POST") {
    setSaving(true);
    try {
      const response = await apiFetch(path, { method, headers: { "content-type": "application/json" }, body: JSON.stringify(body) });
      const json = await response.json();
      if (!response.ok) throw new Error(json.error ?? "Action failed");
      setToast({ message: success }); setModal(null); await load(); return json;
    } catch (caught) { setToast({ message: caught instanceof Error ? caught.message : "Action failed", type: "error" }); return null; }
    finally { setSaving(false); }
  }

  async function createProgram() {
    const tiers = (form.tiers ?? "").split("\n").map((line) => line.trim()).filter(Boolean).map((line) => { const [name, threshold, benefits] = line.split("|").map((part) => part.trim()); return { name, minimumLifetimePoints: Number(threshold || 0), benefits: benefits ? benefits.split(";").map((item) => item.trim()).filter(Boolean) : [] }; });
    const earnRules = (form.earnRules ?? "").split("\n").map((line) => line.trim()).filter(Boolean).map((line) => { const [eventType, points, description] = line.split("|").map((part) => part.trim()); return { eventType, points: Number(points), description: description || null }; });
    await request("/api/loyalty/programs", { name: form.name, description: form.description, definition: { currencyName: form.currencyName, expirationDays: form.expirationDays ? Number(form.expirationDays) : null, maxPointsPerTransaction: Number(form.maxPointsPerTransaction), dailyEarnLimit: Number(form.dailyEarnLimit), fraudReviewThreshold: Number(form.fraudReviewThreshold), referralReward: Number(form.referralReward), earnRules, tiers } }, "Draft loyalty program created");
  }
  async function publish(program: Program) {
    setSaving(true);
    try {
      const detailResponse = await apiFetch(`/api/loyalty/programs/${program.id}`); const detail = await detailResponse.json();
      if (!detailResponse.ok) throw new Error(detail.error ?? "Program versions could not be loaded");
      const draft = detail.data.versions.find((version: { status: string }) => version.status === "draft");
      if (!draft) throw new Error("No draft version is available to publish");
      await request(`/api/loyalty/programs/${program.id}/publish`, { versionId: draft.id }, `${program.name} published`);
    } catch (caught) { setToast({ message: caught instanceof Error ? caught.message : "Publish failed", type: "error" }); }
    finally { setSaving(false); }
  }
  async function createAccount() { await request("/api/loyalty/accounts", { programId: form.programId, contactId: form.contactId }, "Loyalty account created"); }
  async function postTransaction() { await request("/api/loyalty/transactions", { accountId: form.accountId, transactionType: form.transactionType || "earn", points: Number(form.points), sourceType: form.sourceType || "manual", description: form.description, idempotencyKey: globalThis.crypto.randomUUID() }, "Loyalty transaction recorded"); }
  async function createReferral() {
    const json = await request("/api/loyalty/referrals", { programId: form.programId, referrerContactId: form.referrerContactId, referredContactId: form.referredContactId || null, qualificationEvent: form.qualificationEvent }, "Referral created");
    if (json?.data?.referralCode) setOneTimeCode(json.data.referralCode);
  }

  return <AppLayout><div className="space-y-5 p-6">
    <ModuleHeader title="Loyalty" description="Governed rewards, append only points, tiers, referrals, incentives, and fraud review." action={<div className="flex gap-2"><Button variant="outline" icon={RefreshCw} onClick={load}>Refresh</Button><Button variant="gradient" icon={Plus} onClick={() => open("program")}>New program</Button></div>} />
    {error && <ErrorState message={error} retry={load} />}
    {loading || !data ? <LoadingState /> : <>
      <StatGrid columns={6} stats={[
        { label: "Active programs", value: data.summary.activePrograms, icon: Gift },
        { label: "Members", value: data.summary.accounts, icon: Users },
        { label: "Points outstanding", value: number(data.summary.pointsOutstanding), icon: WalletCards, tone: "violet" },
        { label: "Lifetime earned", value: number(data.summary.lifetimeEarned), icon: Sparkles, tone: "green" },
        { label: "Held transactions", value: data.summary.heldTransactions, icon: ShieldAlert, tone: "amber" },
        { label: "Open fraud reviews", value: data.summary.openFraudReviews, icon: AlertTriangle, tone: "red" },
      ]} />
      {oneTimeCode && <div className="rounded-xl border border-amber-500/30 bg-amber-500/10 p-4"><p className="text-xs font-semibold text-amber-300">Referral code shown once</p><div className="mt-2 flex items-center justify-between gap-3"><code className="rounded bg-surface-950 px-3 py-2 font-mono text-sm text-surface-100">{oneTimeCode}</code><Button size="sm" variant="outline" onClick={() => { navigator.clipboard.writeText(oneTimeCode); setToast({ message: "Referral code copied" }); }}>Copy</Button><Button size="sm" variant="ghost" onClick={() => setOneTimeCode("")}>Dismiss</Button></div></div>}
      <div className="flex items-center justify-between gap-3"><FilterTabs value={tab} onChange={setTab} options={[{ value: "accounts", label: "Members", count: data.accounts.length }, { value: "transactions", label: "Point ledger", count: data.transactions.length }, { value: "programs", label: "Programs", count: data.programs.length }, { value: "referrals", label: "Referrals", count: data.referrals.length }, { value: "reviews", label: "Fraud review", count: data.reviews.length }]} /><div className="flex gap-2"><Button size="sm" variant="outline" onClick={() => open("account")}>Add member</Button><Button size="sm" variant="outline" onClick={() => open("transaction")}>Post points</Button><Button size="sm" variant="outline" onClick={() => open("referral")}>Create referral</Button></div></div>

      {tab === "accounts" && <section className="overflow-hidden rounded-xl border border-surface-800 bg-surface-900/50">{data.accounts.length === 0 ? <div className="p-4"><EmptyState icon={Users} title="No loyalty members" description="Publish a program, then enroll an existing customer." /></div> : <div className="divide-y divide-surface-800">{data.accounts.map((account) => <div key={account.id} className="grid grid-cols-[1.4fr_1fr_.7fr_.7fr_.7fr] items-center gap-3 px-4 py-3 text-xs"><div><Link href={`/crm/contacts/${account.contactId}`} className="font-semibold text-surface-100 hover:text-brand-400">{fullName(account.firstName, account.lastName)}</Link><p className="mt-1 text-[10px] text-surface-600">{account.email ?? "No email"} · {account.programName}</p></div><span className="text-surface-300">{account.tierName ?? "Tier unavailable"}</span><strong className="text-surface-100">{number(account.currentBalance)}</strong><span className="text-emerald-400">+{number(account.lifetimeEarned)}</span><span className="text-surface-500">−{number(account.lifetimeRedeemed)}</span></div>)}</div>}</section>}
      {tab === "transactions" && <section className="overflow-hidden rounded-xl border border-surface-800 bg-surface-900/50">{data.transactions.length === 0 ? <div className="p-4"><EmptyState icon={WalletCards} title="No point transactions" description="Posted and held entries appear in this append only ledger." /></div> : <div className="divide-y divide-surface-800">{data.transactions.map((transaction) => { const account = data.accounts.find((item) => item.id === transaction.accountId); return <div key={transaction.id} className="grid grid-cols-[1.2fr_.8fr_.6fr_.8fr_1fr] items-center gap-3 px-4 py-3 text-xs"><span className="text-surface-200">{account ? fullName(account.firstName, account.lastName) : transaction.accountId.slice(0, 8)}</span><StatusBadge value={transaction.transactionType} /><strong className={transaction.points >= 0 ? "text-emerald-400" : "text-red-400"}>{transaction.points >= 0 ? "+" : ""}{number(transaction.points)}</strong><StatusBadge value={transaction.status} /><span className="truncate text-surface-500">{transaction.description ?? transaction.sourceType}</span></div>; })}</div>}</section>}
      {tab === "programs" && <div className="grid grid-cols-1 gap-4 lg:grid-cols-2">{data.programs.length === 0 ? <div className="lg:col-span-2"><EmptyState icon={Gift} title="No loyalty programs" description="Create a governed draft and publish it before enrolling customers." /></div> : data.programs.map((program) => <div key={program.id} className="rounded-xl border border-surface-800 bg-surface-900/50 p-4"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2"><h2 className="text-sm font-semibold text-surface-100">{program.name}</h2><StatusBadge value={program.status} /></div><p className="mt-1 text-[11px] text-surface-500">{program.description || "No description"}</p></div><Award size={18} className="text-amber-400" /></div><div className="mt-4 flex gap-2">{!program.activeVersionId && <Button size="xs" variant="success" loading={saving} onClick={() => publish(program)}>Publish draft</Button>}<Button size="xs" variant="outline" onClick={() => window.location.href = `/loyalty/programs/${program.id}`}>Version history</Button></div></div>)}</div>}
      {tab === "referrals" && <section className="overflow-hidden rounded-xl border border-surface-800 bg-surface-900/50">{data.referrals.length === 0 ? <div className="p-4"><EmptyState icon={Sparkles} title="No referrals" description="Create referrals with one time codes and explicit qualification status." /></div> : <div className="divide-y divide-surface-800">{data.referrals.map((referral) => { const referrer = data.accounts.find((item) => item.contactId === referral.referrerContactId && item.programId === referral.programId); return <div key={referral.id} className="grid grid-cols-[1.2fr_1fr_.7fr_auto] items-center gap-3 px-4 py-3 text-xs"><span className="text-surface-200">{referrer ? fullName(referrer.firstName, referrer.lastName) : referral.referrerContactId.slice(0, 8)}</span><code className="font-mono text-[10px] text-surface-500">{referral.referralCodeHint}</code><StatusBadge value={referral.status} /><div className="flex gap-1">{referral.status === "pending" && <Button size="xs" variant="outline" onClick={() => request(`/api/loyalty/referrals/${referral.id}`, { status: "qualified" }, "Referral qualified", "PATCH")}>Qualify</Button>}{referral.status === "qualified" && <Button size="xs" variant="success" onClick={() => request(`/api/loyalty/referrals/${referral.id}`, { status: "rewarded" }, "Referral rewarded", "PATCH")}>Reward</Button>}</div></div>; })}</div>}</section>}
      {tab === "reviews" && <section className="overflow-hidden rounded-xl border border-surface-800 bg-surface-900/50">{data.reviews.length === 0 ? <div className="p-4"><EmptyState icon={CheckCircle2} title="No open fraud reviews" description="Transactions exceeding published thresholds are held here without changing balances." /></div> : <div className="divide-y divide-surface-800">{data.reviews.map((review) => <div key={review.id} className="flex items-center gap-3 px-4 py-3"><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><StatusBadge value={review.riskLevel} /><span className="font-mono text-[10px] text-surface-600">{review.transactionId?.slice(0, 12) ?? review.referralId?.slice(0, 12)}</span></div><p className="mt-1 text-[11px] text-surface-400">{Array.isArray(review.reasonCodes) ? review.reasonCodes.join(", ") : "Review required"}</p></div><Button size="xs" variant="danger" onClick={() => request(`/api/loyalty/fraud-reviews/${review.id}`, { decision: "rejected", resolutionNotes: "Rejected by operator" }, "Review rejected", "PATCH")}>Reject</Button><Button size="xs" variant="success" onClick={() => request(`/api/loyalty/fraud-reviews/${review.id}`, { decision: "approved", resolutionNotes: "Approved by operator" }, "Review approved", "PATCH")}>Approve</Button></div>)}</div>}</section>}
      <p className="rounded-lg border border-surface-800 bg-surface-900/30 px-4 py-3 text-[11px] text-surface-500">{data.methodology}</p>
    </>}

    <Modal open={modal === "program"} onClose={() => setModal(null)} title="Create loyalty program" width="max-w-2xl"><div className="space-y-4 p-5"><Field label="Program name"><input className={inputClass} value={form.name ?? ""} onChange={(event) => setForm({ ...form, name: event.target.value })} /></Field><Field label="Description"><textarea className={textareaClass} rows={2} value={form.description ?? ""} onChange={(event) => setForm({ ...form, description: event.target.value })} /></Field><div className="grid grid-cols-3 gap-3"><Field label="Point name"><input className={inputClass} value={form.currencyName ?? "Points"} onChange={(event) => setForm({ ...form, currencyName: event.target.value })} /></Field><Field label="Referral reward"><input type="number" className={inputClass} value={form.referralReward ?? "250"} onChange={(event) => setForm({ ...form, referralReward: event.target.value })} /></Field><Field label="Expiration days"><input type="number" className={inputClass} value={form.expirationDays ?? ""} onChange={(event) => setForm({ ...form, expirationDays: event.target.value })} placeholder="No expiration" /></Field></div><div className="grid grid-cols-3 gap-3"><Field label="Max per transaction"><input type="number" className={inputClass} value={form.maxPointsPerTransaction ?? "10000"} onChange={(event) => setForm({ ...form, maxPointsPerTransaction: event.target.value })} /></Field><Field label="Daily earn limit"><input type="number" className={inputClass} value={form.dailyEarnLimit ?? "25000"} onChange={(event) => setForm({ ...form, dailyEarnLimit: event.target.value })} /></Field><Field label="Review threshold"><input type="number" className={inputClass} value={form.fraudReviewThreshold ?? "5000"} onChange={(event) => setForm({ ...form, fraudReviewThreshold: event.target.value })} /></Field></div><Field label="Earn rules" hint="One per line: event.type | points | description"><textarea className={textareaClass} rows={4} value={form.earnRules ?? ""} onChange={(event) => setForm({ ...form, earnRules: event.target.value })} /></Field><Field label="Tiers" hint="One per line: name | lifetime point threshold | benefits separated by semicolons"><textarea className={textareaClass} rows={5} value={form.tiers ?? ""} onChange={(event) => setForm({ ...form, tiers: event.target.value })} /></Field><Button variant="gradient" loading={saving} onClick={createProgram}>Create governed draft</Button></div></Modal>
    <Modal open={modal === "account"} onClose={() => setModal(null)} title="Add loyalty member"><div className="space-y-4 p-5"><Field label="Program"><select className={inputClass} value={form.programId ?? ""} onChange={(event) => setForm({ ...form, programId: event.target.value })}><option value="">Select active program</option>{activePrograms.map((program) => <option key={program.id} value={program.id}>{program.name}</option>)}</select></Field><Field label="Customer"><select className={inputClass} value={form.contactId ?? ""} onChange={(event) => setForm({ ...form, contactId: event.target.value })}><option value="">Select customer</option>{contacts.map((contact) => <option key={contact.id} value={contact.id}>{fullName(contact.firstName, contact.lastName)} · {contact.email ?? "no email"}</option>)}</select></Field><Button variant="gradient" loading={saving} onClick={createAccount}>Add member</Button></div></Modal>
    <Modal open={modal === "transaction"} onClose={() => setModal(null)} title="Post loyalty points"><div className="space-y-4 p-5"><Field label="Member account"><select className={inputClass} value={form.accountId ?? ""} onChange={(event) => setForm({ ...form, accountId: event.target.value })}><option value="">Select member</option>{data?.accounts.map((account) => <option key={account.id} value={account.id}>{fullName(account.firstName, account.lastName)} · {account.programName} · balance {account.currentBalance}</option>)}</select></Field><div className="grid grid-cols-2 gap-3"><Field label="Transaction type"><select className={inputClass} value={form.transactionType ?? "earn"} onChange={(event) => setForm({ ...form, transactionType: event.target.value })}><option value="earn">Earn</option><option value="redeem">Redeem</option><option value="adjustment">Adjustment</option><option value="expiration">Expiration</option><option value="reversal">Reversal</option></select></Field><Field label="Points"><input type="number" className={inputClass} value={form.points ?? ""} onChange={(event) => setForm({ ...form, points: event.target.value })} /></Field></div><Field label="Description"><input className={inputClass} value={form.description ?? ""} onChange={(event) => setForm({ ...form, description: event.target.value })} /></Field><Button variant="gradient" loading={saving} onClick={postTransaction}>Record ledger entry</Button></div></Modal>
    <Modal open={modal === "referral"} onClose={() => setModal(null)} title="Create referral"><div className="space-y-4 p-5"><Field label="Program"><select className={inputClass} value={form.programId ?? ""} onChange={(event) => setForm({ ...form, programId: event.target.value })}><option value="">Select active program</option>{activePrograms.map((program) => <option key={program.id} value={program.id}>{program.name}</option>)}</select></Field><Field label="Referrer"><select className={inputClass} value={form.referrerContactId ?? ""} onChange={(event) => setForm({ ...form, referrerContactId: event.target.value })}><option value="">Select referrer</option>{contacts.map((contact) => <option key={contact.id} value={contact.id}>{fullName(contact.firstName, contact.lastName)} · {contact.email ?? "no email"}</option>)}</select></Field><Field label="Referred customer" hint="Optional until the referral converts"><select className={inputClass} value={form.referredContactId ?? ""} onChange={(event) => setForm({ ...form, referredContactId: event.target.value })}><option value="">Not identified yet</option>{contacts.map((contact) => <option key={contact.id} value={contact.id}>{fullName(contact.firstName, contact.lastName)} · {contact.email ?? "no email"}</option>)}</select></Field><Field label="Qualification event"><input className={inputClass} value={form.qualificationEvent ?? "purchase.completed"} onChange={(event) => setForm({ ...form, qualificationEvent: event.target.value })} /></Field><Button variant="gradient" loading={saving} onClick={createReferral}>Create referral code</Button></div></Modal>
    {toast && <Toast message={toast.message} type={toast.type} />}
  </div></AppLayout>;
}
